# nfspv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: dc01.ad.irdlab.com
    path: /nfs_share/mongo_data
  persistentVolumeReclaimPolicy: Retain
