apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnet-mvc
spec:
  destination:
    namespace: dotnet
    server: https://kubernetes.default.svc
  source:
    path: yamls
    repoURL: https://github.com/rajanup77/k8s-dotnet-mvc
    targetRevision: HEAD
  sources: []
  project: dotnet
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
