apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetmvcdeployment
  namespace: dotnet
spec:
  selector:
    matchLabels:
      name: podkoname
  replicas: 2
  template:
    metadata:
      labels:
        name: podkoname
    spec:
      containers:
      - name: dotnetmvccontainer
        image: rajanup77/dotnet-mvc
        ports:
        - containerPort: 5206
        resources:
           limits:
             cpu: "1"
             memory: 500Mi
           requests:
             cpu: 200m
             memory: 128Mi
