apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetmvcdeployment
  namespace: dotnet
spec:
  selector:
    matchLabels:
      name: podkoname
  replicas: 1
  template:
    metadata:
      labels:
        name: podkoname
    spec:
      containers:
      - name: dotnetmvccontainer
        image: rajanup77/dotnet-mvc:1.0
        ports:
        - containerPort: 5206
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
