apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
  namespace: dotnet
spec:
  selector:
    matchLabels:
      app: dotnet
  replicas: 2
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
      - name: dotnet
        image: rajanup77/dotnet-mvc
        ports:
        - containerPort: 5206

