apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
  namespace: dotnet
spec:
  selector:
    matchLabels:
      name: podkoname
  replicas: 2
  template:
    metadata:
      labels:
        name: podkoname
    spec:
      containers:
      - name: dotnet-container
        image: rajanup77/dotnet-mvc
        ports:
        - containerPort: 5206

