apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dotnet-hpa
  namespace: dotnet
spec:
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 20
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 200Mi
        type: AverageValue
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dotnetmvcdeployment
