apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodbpod
  template:
    metadata:
      labels:
        app: mongodbpod
    spec:
      containers:
        - name: mongodbcontainer
          image: mongo:7.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongo
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: Mongo@123
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: nfspvc
